### ISSUE TITLE
REI Network: <need to recover rei>

### ISSUE THREAD

**Issue by ehincapiem** [REI-Network/rei-scan#2]
*Describe your issue here.*

Transaction hash id

0x4ae68a4418a428701c85bbd55029375d4fc202f4f71daef067dbffca7cee51e6

Transaction Hash
0x4ae68a4418a428701c85bbd55029375d4fc202f4f71daef067dbffca7cee51e6
 Result
 Success
 Status
Confirmed Confirmed by 988,539
 Block
[4528240](https://scan.rei.network/block/4528240)
 Timestamp
 a month ago | June-05-2022 05:04:49 PM +-5 UTC | Confirmed within <= 3.0 seconds
 From
[0xe1a5c0be49c5ad6cded72ee9b04e995f3a8aae75](https://scan.rei.network/address/0xe1a5c0be49c5ad6cded72ee9b04e995f3a8aae75)
 To
[0xe380cde75bd71fd4c3a33639944dc595d87d82d5](https://scan.rei.network/address/0xe380cde75bd71fd4c3a33639944dc595d87d82d5)
 Value
35.97 REI ($1.63 USD)
 Transaction Fee
0.000021 REI (Less than $0.000001 USD)
 Gas Price
1 Gwei

I was unable to add rei token to coinbase, now my address has changed to

0xee21237cff4c12a2881501263c27f8a165d85125

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Linux; Android 11; moto g(9) play) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by samlior** [comment]
REI is not ERC20 and cannot be added to a third-party wallet, please use MetaMask wallet instead
