### ISSUE TITLE
REI Network: <Issue Title>

### ISSUE THREAD

**Issue by azeed6236** [REI-Network/rei-scan#6]
*Describe your issue here.*

### Environment
* Elixir Version: 1.13.4
* Erlang Version: 24
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/106.0.5249.92 Mobile/15E148 Safari/604.1`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*
‏سلام عليكم سيدي كيف يمكنني اضافة عملت rei networkفي محفظة تراست ووالت

**Comment by azeed6236** [comment]
قل لنا ماذا يحدث بدلا من ذلك. 
سلام عليكم سيدي كيف اضافة عملت rei في محفظة تراست ووالت

**Comment by samlior** [comment]
REI is not ERC20 and cannot be added to a third-party wallet, please use MetaMask wallet instead
